modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="uraniumcraft"
version="1.0.0"
displayName="uraniumcraft"
credits="created by lolmoag and frivolus"
displayURL="https://mcreator.net"
authors="lolmoag"
description="a mod based on the radioactive systeme"

[[dependencies.uraniumcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.uraniumcraft]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

